### ISSUE TITLE
I didn't understood DisableVirtualPathProvider configuration?

### ISSUE THREAD

**Issue by croban** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#100]
First of all, if I turn DisableVirtualPathProvider to true, filename which is saved inside filesystem has absolute url inside DB. That I don't understand, why would I like to have absulteurl inside filename?
This absolute url will be also moved forward to cache. 

What does VirtualPathProvider does, abstract: it works as a proxy, download file from azure storage and forward response, for each requst which comes for /media/*, if that was SEO consideration, they should just add custom storage domain something like: media.projectname.com. I don't see any other reason why I would  like to have VirtualPathProvider between my application and storage... I did't get it or?

And other question maybe related to https://github.com/JimBobSquarePants/ImageProcessor can ImageProcessor write directly to Media/FILDID/ folder?

**Comment by JimBobSquarePants** [comment]
>First of all, if I turn DisableVirtualPathProvider to true, filename which is saved inside filesystem has absolute url inside DB. That I don't understand, why would I like to have absulteurl inside filename?
This absolute url will be also moved forward to cache.

Yes. That the default Umbraco behaviour, it'll store the full URL to the media file. 

The VirtualPathProvider performs a redirect from a relative path to an absolute one. It's not for SEO, it's for transferring the environment so that dev => staging => hosting can all have the same relative media paths.

>And other question maybe related to https://github.com/JimBobSquarePants/ImageProcessor can ImageProcessor write directly to Media/FILDID/ folder

No. ImageProcessor.Web is not an Umbraco library. I have no idea why people keep thinking it is.
