### ISSUE TITLE
Change configuration for different environments

### ISSUE THREAD

**Issue by sgisbert** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#36]
Hi,

this is more a question rather than an issue. The case here is that we have different storage accounts for the different environments the app has (DEV, QA, UAT and PROD).
If the config settings were in the web.config, it would be easy to set up a transformation to change the settings on every env, but as it's in a different config file, I cannot find the way to do it.

2 options here:
- Have you managed to add transformations to .config files other than web.config?
- Can you change settings at runtime? Binding an event to ApplicationInit, as described here: https://our.umbraco.org/documentation/Reference/Events/application-startup?

Many thanks!
Sergi

**Comment by JimBobSquarePants** [comment]
Hi Sergi,

While it would be possible to add the configuration to the web.config (There' an open PR doing so) I'm not inclined to go for it. Umbraco places the configuration within the FileSystemProviders.config and I believe we should keep ours there for compatibility.

It is possible to perform transforms on other config files but you have to do it manually for it to work properly.

Create the following files and add them to your proj file (unload, edit) as follows:

``` xml
<Content Include="Config\FileSystemProviders.config">
    <SubType>Designer</SubType>
</Content>
<None Include="Config\FileSystemProviders.Debug.config">
    <DependentUpon>FileSystemProviders.config</DependentUpon>
</None>
<None Include="Config\FileSystemProviders.QA.config">
    <DependentUpon>FileSystemProviders.config</DependentUpon>
</None>
<None Include="Config\FileSystemProviders.UATMaster.config">
    <DependentUpon>FileSystemProviders.config</DependentUpon>
</None>
<None Include="Config\FileSystemProviders.UATFrontEnd.config">
    <DependentUpon>FileSystemProviders.config</DependentUpon>
</None>
<None Include="Config\FileSystemProviders.ProductionFrontEnd.config">
    <DependentUpon>FileSystemProviders.config</DependentUpon>
</None>
<None Include="Config\FileSystemProviders.ProductionMaster.config">
    <DependentUpon>FileSystemProviders.config</DependentUpon>
</None>
```
Then in your proj file you will need to add a task, something like as follows. (You might need to tweak the output folder if you are building locally instead of CI)

``` xml
<UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\Web\Microsoft.Web.Publishing.Tasks.dll" />
<!--Moving these from AfterBuild to Before build ensures that the target is always ran-->
<Target Name="BeforeBuild">
  <!--Generate transformed config in the output directory-->
  <TransformXml Source="Config\FileSystemProviders.config" Transform="Config\FileSystemProviders.$(Configuration).config" Destination="Config\FileSystemProviders.config" StackTrace="true" />
</Target>
```
If you configure your transforms as you would for the web.config this will work in the same manner.

E.g

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<FileSystemProviders xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <!-- Media -->
  <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
    <Parameters>
      <add key="rootUrl" value="[url]" xdt:Transform="SetAttributes" xdt:Locator="Match(key)"/>
      <add key="connectionString"
  			value="DefaultEndpointsProtocol=https;AccountName=[name];AccountKey=[key]"
        xdt:Transform="SetAttributes" xdt:Locator="Match(key)"/>
    </Parameters>
  </Provider>
</FileSystemProviders>
```
Hope this helps.

James
