### ISSUE TITLE
Image resizing in media folder not working

### ISSUE THREAD

**Issue by aucklandtransport** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#49]
Image resizing for azure blob always returns original image. (not resize)
For example www.site.com/media/1234/abc.jpg?width=100 will not resize (image from azure blob)

But for local files resizing works:
For example www.site.com/otherfolder/abc.jpg?width=100 works. (there is a static abc.jpg in otherfolder)

Configuation is default from umbraco package installer.

**Comment by JimBobSquarePants** [comment]
Hi there,

Would you be able to provide some more detail please. It's impossible to debug your scenario without at least a sample of how your configuration files are setup and the appropriate version numbers.

**Comment by aucklandtransport** [comment]
I have found the root of the issue.

Config/imageprocessor/security.config:
<service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="Container" value="media"/>
        <setting key="MaxBytes" value="32194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://xxx.blob.core.windows.net/media/"/>
      </settings>
    </service>

The host value cannot have /media/ at the end ie (http://xxx.blob.core.windows.net/media/) if container value is already defined.

The sample config file is misleading, as container is '', and the host value having the container at the end. ie (http://[account].blob.core.windows.net/media/), defining container value will fail.

**Comment by JimBobSquarePants** [comment]
Interesting... Here's the exact config copy/pasted from a working solution with the name changed to protect the client. 

Image requests are always made with the leading `/` e.g. `/media/1131/image.jpg?width=300`

```
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304" />
        <setting key="Timeout" value="30000" />
        <setting key="Host" value="https://workingwebsite.blob.core.windows.net/media/" />
      </settings>
    </service>
```

This is running the 0.5.1 beta

I have noticed you added an erroneous `container` key/value pair to the config but that shouldn't be an issue.

What version are you running? I wonder whether something has changed since the version I am using?

**Comment by aucklandtransport** [comment]
```
<package id="UmbracoFileSystemProviders.Azure" version="0.5.3-beta" targetFramework="net45" />
<package id="ImageProcessor" version="2.4.3.0" targetFramework="net45" />
<package id="ImageProcessor.Web" version="4.6.3.0" targetFramework="net45" />
```
The sample config file was generated by umbraco backoffice package installer

**Comment by JimBobSquarePants** [comment]
Thanks... I'll have a look asap to see what changed and update the docs if it was a necessary change or revert otherwise. @Jeavon Any ideas?

**Comment by Jeavon** [comment]
@JimBobSquarePants Hmm, I think the container element was added on a upgrade of ImageProcessor.Web.Config from v2.2.2.0 to v2.2.5.0. But the UmbracoFileSystemProviders.Azure Umbraco installer doesn't use the container element it continues to add the container to the Host url which is fine but I guess it's recommended to use the container element now it's there instead of adding it to the Host element?

**Comment by JimBobSquarePants** [comment]
Silly boy! I totally forgot... It's tricky keeping up with all the moving parts sometimes. 

Yeah, I would always use the Container element, we'll just have to update the documentation to reflect version changes.
