### ISSUE TITLE
Does this work with 7.6.5

### ISSUE THREAD

**Issue by brianmrush** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#90]
Question if this works with 7.6.5.  It seems uploading images works from umbraco but when I try to see the images it fails

I have this in my config 

    <add key="AzureBlobFileSystem.RootUrl:media" value="https://images.openskycc.com/" />
    <add key="AzureBlobFileSystem.MaxDays:media" value="365" />

I tried both 
<add key="AzureBlobFileSystem.DisableVirtualPathProvider" value="true" />
and 
<add key="AzureBlobFileSystem.DisableVirtualPathProvider" value="false" />

It seems that when I click on the image from umbraco it is using a relative path but that relative path is not pointing to the azure location

Thoughts?

**Comment by JimBobSquarePants** [comment]
Should work with 7.6.5 yeah. Can you check you config settings against the examples in the read me and let me know if you spot anything.

**Comment by caterwomtious** [comment]
I just hit the same problem with 7.6.12, and it was due to the following line being missing in /media/web.config

`<add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler"/>`

I think I removed that by mistake when comparing files before and after the upgrade, so I don't think there's anything wrong with either Umbraco or this project in this case.

**Comment by JimBobSquarePants** [comment]
Thanks @caterwomtious for the extra info, much appreciated. I'm gonna close this then.
